{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ include "ondemand-user-account.generatedNamespace" . }}
  annotations:
    "helm.sh/hook": post-install
    helm.sh/resource-policy: keep
  labels:
    {{- include "ondemand-user-account.labels" . | nindent 4 }}
  {{- if .Values.certificate.extraLabels }}
    {{- toYaml .Values.certificate.extraLabels | nindent 4 -}}
  {{- end }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ .Values.certificate.issuer.kind }}
  dnsNames:
    - "{{ include "ondemand-user-account.generatedNamespace" . }}.{{ .Values.certificate.dnsDomain }}"
    - "*.{{ include "ondemand-user-account.generatedNamespace" . }}.{{ .Values.certificate.dnsDomain }}"
{{- end }}